using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace csharp
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    /// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
    /// </summary>
    public class Q002 : IEulerProblem
    {
        public string Solve()
        {
            int num = 0;
            int[] arr = new int[40000];
            int a = 0, b = 1, c = 1, i = 0;
            while (num < 4000000)
            {
                num = c + b;
                if (num < 4000000 && num % 2 == 0)
                {
                    arr[++i] = num;
                }
                a = b; // 1 // 1 // 2
                b = c; // 1 // 2 // 3
                c = a + b; // 2 // 3 // 5
            }
            int sum = 0;
            for (int j = 0; j < arr.Length; j++)
                sum += arr[j];
            return sum.ToString();
        }
    }
}
